<a href="https://colab.research.google.com/github/Karan15504/Civil-Aviation-Dashboard/blob/main/Civil_Aviation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [125]:
df = pd.read_excel("/content/DOM CITYPAIR DATA, JANUARY  2026 (2).xlsx", skiprows = 2)


In [126]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df

,s.no.,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2
0,1,ADAMPUR,MUMBAI,5278,5380,0,0.083,0,0
1,2,ADAMPUR,NANDED,578,-,0,-,0,-
2,3,ADAMPUR,Ghaziabad,1139,1514,0,0,0,0
3,4,AGARTALA,AHMEDABAD,-,206,-,0.793,-,0
4,5,AGARTALA,BAGDOGRA,2221,4287,0,0,0,0
...,...,...,...,...,...,...,...,...,...
654,655,MUMBAI,CHENNAI,4458,3289,2.42,0,0,0
655,656,MUMBAI,LUCKNOW,5026,5083,1.087,0,0,0
656,657,MUMBAI,HYDERABAD,7035,6732,6.588,0,0,0
657,SUB TOTAL,NaN,NaN,7569183,7678005,43590.979721,37495.697919,1942.942072,1711.465007


In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659 entries, 0 to 658
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   s.no.                    659 non-null    object
 1   city 1                   657 non-null    object
 2   city 2                   657 non-null    object
 3   passengers 
to city 2    659 non-null    object
 4   passengers 
from city 2  658 non-null    object
 5   freight 
to city 2       659 non-null    object
 6   freight 
from city 2     658 non-null    object
 7   mail 
to city 2          659 non-null    object
 8   mail 
from city 2        658 non-null    object
dtypes: object(9)
memory usage: 46.5+ KB


In [128]:
mask = ~df.astype(str).apply(lambda row: row.str.contains('SUB TOTAL|^TOTAL$', case=False).any(), axis=1)
df = df[mask]

In [129]:
df

,s.no.,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2
0,1,ADAMPUR,MUMBAI,5278,5380,0,0.083,0,0
1,2,ADAMPUR,NANDED,578,-,0,-,0,-
2,3,ADAMPUR,Ghaziabad,1139,1514,0,0,0,0
3,4,AGARTALA,AHMEDABAD,-,206,-,0.793,-,0
4,5,AGARTALA,BAGDOGRA,2221,4287,0,0,0,0
...,...,...,...,...,...,...,...,...,...
652,653,MUMBAI,JAIPUR,4799,4893,2.212,4.205,0,0
653,654,MUMBAI,MANGALORE,3711,4211,0,0.001,0,2.647
654,655,MUMBAI,CHENNAI,4458,3289,2.42,0,0,0
655,656,MUMBAI,LUCKNOW,5026,5083,1.087,0,0,0


In [130]:
df.drop("s.no.", axis=1,inplace = True)


In [131]:
df['OD Pair'] = df['city 1'] + "-" + df['city 2']

In [132]:
df["passengers \nto city 2"].dtypes

dtype('O')

In [133]:
df["passengers \nfrom city 2"].dtypes

dtype('O')

In [134]:
df["passengers \nto city 2"].unique()

array([5278, 578, 1139, '-', 2221, 4007, 327, 6524, 858, 10097, 3245,
       1674, 35231, 797, 936, 1529, 2945, 171, 2157, 5358, 2076, 2626,
       1688, 4520, 5381, 1704, 50114, 4173, 4845, 10401, 27804, 4431,
       17061, 5183, 107213, 160, 2398, 118, 13432, 5060, 24239, 6464,
       10644, 519, 3077, 1276, 1532, 284, 5126, 258, 31727, 12484, 91101,
       1637, 2246, 6059, 326, 22044, 4484, 5140, 6396, 4349, 202, 3465,
       5323, 2565, 6531, 6382, 5683, 107, 402, 630, 1170, 1599, 482, 3753,
       892, 189, 5110, 1578, 10547, 4953, 183, 49163, 203, 2527, 2061,
       155, 14410, 4146, 5894, 2336, 45, 931, 13368, 2323, 10213, 21388,
       746, 5951, 55188, 4089, 434, 1315, 16343, 3469, 28407, 25279, 2308,
       3304, 4399, 3840, 2056, 490, 10824, 43447, 1485, 24191, 62794,
       18012, 45539, 814, 9025, 207251, 4842, 296, 5834, 33571, 12097,
       37994, 4462, 4149, 89055, 394, 20161, 4118, 36636, 5188, 2693,
       4438, 10940, 5123, 3688, 62865, 2038, 85825, 20828, 245, 2931

In [135]:
df["passengers \nto city 2"] = df["passengers \nto city 2"].replace("-",0)


In [136]:
df["passengers \nto city 2"] = df["passengers \nto city 2"].astype(int)

In [137]:
df["passengers \nto city 2"].dtypes

dtype('int64')

In [138]:
df["passengers \nfrom city 2"].unique()

array([5380, '-', 1514, 206, 4287, 4382, 320, 6970, 777, 10530, 3410,
       1712, 41179, 471, 1021, 1891, 3646, 334, 2168, 4780, 60, 2123,
       2804, 1908, 4369, 4908, 1563, 49110, 4306, 5031, 10201, 27144,
       4682, 17048, 4787, 106908, 244, 2323, 157, 14219, 4945, 22980,
       6427, 10284, 494, 3123, 1313, 1814, 216, 5219, 269, 29607, 11691,
       89237, 4211, 1481, 2257, 4783, 354, 22594, 5048, 5035, 5765, 17,
       5140, 2684, 4989, 2499, 5363, 4872, 5364, 30, 173, 750, 1386, 1632,
       497, 3337, 941, 314, 4564, 1574, 11410, 5502, 172, 51031, 2752,
       2165, 105, 14798, 4218, 5072, 2210, 73, 924, 12917, 1754, 10403,
       17105, 711, 6644, 54853, 4206, 374, 6790, 16639, 4852, 28386,
       26959, 2160, 3356, 4176, 3381, 2043, 450, 11603, 45314, 1639,
       24098, 67618, 18810, 50103, 863, 9075, 208730, 4924, 462, 5924,
       37029, 12133, 32115, 4555, 4406, 90026, 407, 20634, 4302, 36370,
       5150, 2982, 4691, 10993, 6300, 4039, 66286, 2140, 86172, 22195,
     

In [139]:
df["passengers \nfrom city 2"] = df["passengers \nfrom city 2"].replace("-",0)

df["passengers \nfrom city 2"] = df["passengers \nfrom city 2"].astype(int)

In [140]:
df["passengers \nfrom city 2"].dtypes

dtype('int64')

In [141]:
df['freight \nto city 2'].dtypes

dtype('O')

In [142]:
df["freight \nto city 2"].unique()

array([0, '-', 19.084, 0.003, 15.369, 0.081, 3.025, 7.662, 0.335, 16.058,
       0.169, 0.846, 1.018, 0.04, 0.044, 0.306, 9.0749,
       459.53163000000006, 0.086, 21.948, 22.889, 246.19710000000003,
       26.23, 10.255, 3.685, 1867.3134954999996, 1.506, 0.061, 0.278,
       16.235, 26.041, 170.168, 0.2, 5.083, 2.773, 35.497, 256.88371,
       45.201, 950.5565522999999, 0.055, 40.698, 82.16307, 19.08, 10.113,
       0.901, 5.229, 2.3, 0.002, 13.328, 2.471, 32.542, 0.056, 0.046,
       11.604, 0.119, 35.6705, 5.853, 3.8914999999999997, 3.625, 0.382,
       51.77973, 12.395, 101.59169, 0.347, 2.315, 40.633, 31.85649,
       30.62787, 0.049, 0.072, 0.012, 32.079, 151.51708,
       216.13400000000001, 846.56747, 31.3, 91.96, 0.432, 7.626,
       3472.7106776, 0.075, 19.591, 17.939, 62.45451, 211.62536, 0.62,
       502.82, 3.367, 90.11, 0.354, 186.617, 0.447, 0.188, 11.307,
       0.5489999999999999, 1.508, 289.046, 0.171, 1156.9180299999998,
       19.651, 319.043, 1.02, 6.27999999999999

In [143]:
df["freight \nto city 2"] = df["freight \nto city 2"].replace("-",0)

In [144]:
df["freight \nto city 2"].dtypes


dtype('float64')

In [145]:
df["freight \nfrom city 2"].dtypes

dtype('O')

In [146]:
df["freight \nfrom city 2"].unique()

array([0.083, '-', 0, 0.793, 6.047, 0.001, 45.264, 0.021, 54.803, 1.805,
       21.513, 222.37400000000002, 0.268, 0.016, 3.03, 0.566, 0.426,
       12.977, 22.403, 337.65824, 1.433, 33.558, 234.34387, 23.671, 9.189,
       0.167, 1508.0505969, 0.823, 4.53, 2.622, 6.568, 88.413, 0.055,
       6.521, 17.743, 154.90432, 17.35, 686.6918835, 0.106, 2.624,
       122.619, 0.489, 4.435, 0.241, 0.4, 8.6, 2.051, 23.16, 5.361, 7.449,
       0.941, 1.631, 0.224, 1.108, 1.921, 0.322, 26.9555, 0.175, 0.279,
       27.1705, 1.313, 1.354, 1.302, 109.88250000000001, 0.13, 9.657,
       12.693, 3.64, 309.11385, 0.044, 27.046110000000002, 10.219,
       22.439159999999998, 66.92272, 0.04, 0.49, 0.197, 0.835, 0.003,
       15.793, 32.636, 156.768, 558.2062099999999, 18.691, 37.385, 3.631,
       4251.964875199999, 0.169, 20.717, 57.114, 29.68638, 101.35647,
       0.622, 151.98700000000002, 19.47, 39.592, 0.002,
       263.71999999999997, 7.091, 0.632, 1.051, 98.315, 0.209, 829.69985,
       0.142, 93.7

In [147]:
df["freight \nfrom city 2"] = df["freight \nfrom city 2"].replace("-",0)

In [148]:
df["freight \nfrom city 2"].dtypes

dtype('float64')

In [149]:
df["mail \nto city 2"].dtypes

dtype('O')

In [150]:
df["mail \nto city 2"].unique()

array([0, '-', 1.375, 1.625, 4.149, 0.004, 2.183, 2.263, 0.286, 3.766,
       1.89, 1.662, 0.544, 7.185799999999999, 0.595, 1.783, 0.69, 1.292,
       0.006, 1.084, 2.601, 18.8166, 0.643, 2.767, 3.53684, 1.188, 1.523,
       0.858, 0.256, 8.26, 10.147, 1.223, 0.015, 0.5, 0.711, 0.08, 1.231,
       1.381, 3.417, 0.666, 8.15, 2.074, 8.022, 11.842699999999999, 8.774,
       18.024, 7.178, 1.542, 5.493, 24.066989999999997, 2.4256, 14.25108,
       0.244, 31.564, 4.126, 4.258, 11.952, 0.23, 2.828, 0.148, 19.884,
       16.409, 0.757, 15.41, 2.681, 13.158, 15.20406, 4.667, 0.679,
       16.095, 1.176, 12.843300000000001, 7.134, 2.167, 3.034, 0.685,
       0.952, 0.507, 0.88, 10.43, 4.024, 4.958880000000001, 2.842, 6.081,
       15.007190000000001, 0.521, 4.648, 1.402, 1.586, 0.089, 5.27558,
       0.59, 5.797, 0.192, 0.052, 7.539, 2.287, 5.21, 0.536, 0.024, 0.136,
       17.936999999999998, 1.097, 1.072, 7.775163000000001, 0.501,
       4.2059999999999995, 1.389, 1.11, 1.994, 0.612, 24.70723

In [151]:
df["mail \nto city 2"] = df["mail \nto city 2"].replace("-",0)

In [152]:
df["mail \nto city 2"].dtype

dtype('float64')

In [153]:
df["mail \nfrom city 2"].dtypes

dtype('O')

In [154]:

df["mail \nfrom city 2"].unique()

array([0, '-', 0.567, 4.984, 5.07576, 0.001, 1.281, 0.149,
       7.419040000000001, 0.818, 1.007, 1.26, 4.486, 1.062, 0.229, 0.233,
       22.274900000000002, 0.066, 0.045, 2.011, 1.488, 2.384,
       1.7206100000000002, 2.322, 39.585827, 6.746, 3.264, 2.089, 0.085,
       1.055, 0.131, 1.336, 4.487, 6.635, 1.25, 0.638, 24.332, 7.186,
       1.918, 0.02612, 0.253, 4.12394, 0.005, 0.043, 7.5611, 1.07, 20.785,
       1.952, 0.127, 0.569, 6.3889, 2.14202, 0.941, 4.699,
       6.8729499999999994, 2.052, 0.054, 21.496, 2.469, 1.139, 0.809,
       40.709737000000004, 0.133, 5.08455, 0.929, 30.337, 1.729, 2.412,
       2.167, 11.512, 6.91391, 2.268, 1.654, 118.159, 34.119792000000004,
       5.721, 0.161, 0.452, 4.051, 1.5, 3.346, 0.013, 2.084, 6.068, 0.291,
       0.3, 1.104, 5.04, 19.54835, 0.279, 17.879002, 0.961, 6.785, 0.082,
       22.11047, 1.49, 9.546, 11.835, 2.27, 11.021, 0.561, 0.492, 10.679,
       0.306, 26.642980000000005, 0.546, 5.402, 0.686, 0.955, 3.537,
       12.18317, 1.6

In [155]:
df["mail \nfrom city 2"] = df["mail \nfrom city 2"].replace("-",0)

In [156]:
df["mail \nfrom city 2"].dtypes

dtype('float64')

In [157]:
print(df.columns.tolist())

['city 1', 'city 2', 'passengers \nto city 2', 'passengers \nfrom city 2', 'freight \nto city 2', 'freight \nfrom city 2', 'mail \nto city 2', 'mail \nfrom city 2', 'OD Pair']


In [158]:
df.isnull().sum()

,0
city 1,0
city 2,0
passengers \nto city 2,0
passengers \nfrom city 2,0
freight \nto city 2,0
freight \nfrom city 2,0
mail \nto city 2,0
mail \nfrom city 2,0
OD Pair,0


In [159]:
df= df.sort_values( by =("OD Pair"))

In [160]:
df

,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2,OD Pair
2,ADAMPUR,Ghaziabad,1139,1514,0.000,0.000,0.00,0.0,ADAMPUR-Ghaziabad
0,ADAMPUR,MUMBAI,5278,5380,0.000,0.083,0.00,0.0,ADAMPUR-MUMBAI
1,ADAMPUR,NANDED,578,0,0.000,0.000,0.00,0.0,ADAMPUR-NANDED
3,AGARTALA,AHMEDABAD,0,206,0.000,0.793,0.00,0.0,AGARTALA-AHMEDABAD
4,AGARTALA,BAGDOGRA,2221,4287,0.000,0.000,0.00,0.0,AGARTALA-BAGDOGRA
...,...,...,...,...,...,...,...,...,...
639,TIRUPATI,VIJAYAWADA,1380,1647,0.104,0.018,0.24,0.0,TIRUPATI-VIJAYAWADA
640,TIRUPATI,VISAKHAPATNAM,2066,2180,0.001,0.105,0.00,0.2,TIRUPATI-VISAKHAPATNAM
641,TRIVANDRUM,VISAKHAPATNAM,38,0,0.000,0.000,0.00,0.0,TRIVANDRUM-VISAKHAPATNAM
642,VARANASI,VISAKHAPATNAM,415,395,0.000,0.068,0.00,0.0,VARANASI-VISAKHAPATNAM


In [161]:
df["OD pair2"] = df["city 2"] + "-" + df["city 1"]

In [162]:
df

,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2,OD Pair,OD pair2
2,ADAMPUR,Ghaziabad,1139,1514,0.000,0.000,0.00,0.0,ADAMPUR-Ghaziabad,Ghaziabad-ADAMPUR
0,ADAMPUR,MUMBAI,5278,5380,0.000,0.083,0.00,0.0,ADAMPUR-MUMBAI,MUMBAI-ADAMPUR
1,ADAMPUR,NANDED,578,0,0.000,0.000,0.00,0.0,ADAMPUR-NANDED,NANDED-ADAMPUR
3,AGARTALA,AHMEDABAD,0,206,0.000,0.793,0.00,0.0,AGARTALA-AHMEDABAD,AHMEDABAD-AGARTALA
4,AGARTALA,BAGDOGRA,2221,4287,0.000,0.000,0.00,0.0,AGARTALA-BAGDOGRA,BAGDOGRA-AGARTALA
...,...,...,...,...,...,...,...,...,...,...
639,TIRUPATI,VIJAYAWADA,1380,1647,0.104,0.018,0.24,0.0,TIRUPATI-VIJAYAWADA,VIJAYAWADA-TIRUPATI
640,TIRUPATI,VISAKHAPATNAM,2066,2180,0.001,0.105,0.00,0.2,TIRUPATI-VISAKHAPATNAM,VISAKHAPATNAM-TIRUPATI
641,TRIVANDRUM,VISAKHAPATNAM,38,0,0.000,0.000,0.00,0.0,TRIVANDRUM-VISAKHAPATNAM,VISAKHAPATNAM-TRIVANDRUM
642,VARANASI,VISAKHAPATNAM,415,395,0.000,0.068,0.00,0.0,VARANASI-VISAKHAPATNAM,VISAKHAPATNAM-VARANASI


In [163]:
df[['city3', 'city4']] = df['OD pair2'].str.split('-', expand=True)

In [164]:
df1= df[["OD Pair", "city 1","city 2" , "passengers \nto city 2" , "freight \nto city 2" , "mail \nto city 2"]]

In [165]:
df2= df[["OD pair2","city3", "city4", "passengers \nfrom city 2",	"freight \nfrom city 2"	,"mail \nfrom city 2"]]

In [166]:
df1.columns=["OD PAIRS", "city 1" , "city2", "passengers" , "freight", "mail"]

In [167]:





df2.columns=["OD PAIRS", "city 1" , "city2", "passengers" , "freight", "mail"]

In [168]:
df_final=pd.concat([df1,df2], axis= 0)

In [169]:
df_final = df_final.melt(
    id_vars=df_final.columns[:3],
    value_vars=df_final.columns[3:],
    var_name='type',
    value_name='value'
)

In [170]:
print(df_final.columns.tolist())

['OD PAIRS', 'city 1', 'city2', 'type', 'value']


In [171]:
df_final

,OD PAIRS,city 1,city2,type,value
0,ADAMPUR-Ghaziabad,ADAMPUR,Ghaziabad,passengers,1139.0
1,ADAMPUR-MUMBAI,ADAMPUR,MUMBAI,passengers,5278.0
2,ADAMPUR-NANDED,ADAMPUR,NANDED,passengers,578.0
3,AGARTALA-AHMEDABAD,AGARTALA,AHMEDABAD,passengers,0.0
4,AGARTALA-BAGDOGRA,AGARTALA,BAGDOGRA,passengers,2221.0
...,...,...,...,...,...
3937,VIJAYAWADA-TIRUPATI,VIJAYAWADA,TIRUPATI,mail,0.0
3938,VISAKHAPATNAM-TIRUPATI,VISAKHAPATNAM,TIRUPATI,mail,0.2
3939,VISAKHAPATNAM-TRIVANDRUM,VISAKHAPATNAM,TRIVANDRUM,mail,0.0
3940,VISAKHAPATNAM-VARANASI,VISAKHAPATNAM,VARANASI,mail,0.0


In [172]:
df_final=df_final.sort_values(by=["OD PAIRS"])

In [180]:
df_final[df_final["OD PAIRS"]=="MUMBAI-JAIPUR"]

,OD PAIRS,city 1,city2,type,value
596,MUMBAI-JAIPUR,MUMBAI,JAIPUR,passengers,4799.00000
3224,MUMBAI-JAIPUR,MUMBAI,JAIPUR,mail,0.00000
1166,MUMBAI-JAIPUR,MUMBAI,JAIPUR,passengers,59962.00000
2480,MUMBAI-JAIPUR,MUMBAI,JAIPUR,freight,330.70365
3794,MUMBAI-JAIPUR,MUMBAI,JAIPUR,mail,20.85720
1910,MUMBAI-JAIPUR,MUMBAI,JAIPUR,freight,2.21200


In [182]:
pd.set_option('display.max_rows', None)

In [188]:
df_final[df_final["OD PAIRS"]=="JAIPUR-MUMBAI"]

,OD PAIRS,city 1,city2,type,value
1823,JAIPUR-MUMBAI,JAIPUR,MUMBAI,freight,355.139842
1253,JAIPUR-MUMBAI,JAIPUR,MUMBAI,passengers,4893.000000
2567,JAIPUR-MUMBAI,JAIPUR,MUMBAI,freight,4.205000
509,JAIPUR-MUMBAI,JAIPUR,MUMBAI,passengers,58116.000000
3137,JAIPUR-MUMBAI,JAIPUR,MUMBAI,mail,4.993000
3881,JAIPUR-MUMBAI,JAIPUR,MUMBAI,mail,0.000000
